"""init

Revision ID: d5d215ae851b
Revises:
Create Date: 2026-02-01 00:00:00.000000

"""


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d215ae851b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rd_cases',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('external_project_id', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_rd_cases_external_project_id'), 'rd_cases', ['external_project_id'], unique=False)
    op.create_index(op.f('ix_rd_cases_status'), 'rd_cases', ['status'], unique=False)
    op.create_index(op.f('ix_rd_cases_tenant_id'), 'rd_cases', ['tenant_id'], unique=False)
    op.create_table('rd_case_items',
    sa.Column('case_item_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('external_item_id', sa.String(length=200), nullable=False),
    sa.Column('internal_item_code', sa.String(length=100), nullable=True),
    sa.Column('intended_use_in_project', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['rd_cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_item_id')
    )
    op.create_index(op.f('ix_rd_case_items_case_id'), 'rd_case_items', ['case_id'], unique=False)
    op.create_index(op.f('ix_rd_case_items_external_item_id'), 'rd_case_items', ['external_item_id'], unique=False)
    op.create_index(op.f('ix_rd_case_items_internal_item_code'), 'rd_case_items', ['internal_item_code'], unique=False)
    op.create_table('rd_case_profiles',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('use_requirements_raw', sa.Text(), nullable=True),
    sa.Column('end_user_requirements_raw', sa.Text(), nullable=True),
    sa.Column('intended_markets', sa.JSON(), nullable=True),
    sa.Column('tech_domains', sa.JSON(), nullable=True),
    sa.Column('project_country_risk', sa.String(length=30), nullable=True),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['rd_cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_rd_case_profiles_case_id'), 'rd_case_profiles', ['case_id'], unique=False)
    op.create_index(op.f('ix_rd_case_profiles_input_fingerprint'), 'rd_case_profiles', ['input_fingerprint'], unique=False)
    op.create_index(op.f('ix_rd_case_profiles_version_no'), 'rd_case_profiles', ['version_no'], unique=False)
    op.create_table('rd_assessments',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('performed_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('recommendation', sa.String(length=50), nullable=False),
    sa.Column('tech_risk_score', sa.Integer(), nullable=False),
    sa.Column('use_risk_score', sa.Integer(), nullable=False),
    sa.Column('end_user_risk_score', sa.Integer(), nullable=False),
    sa.Column('regulatory_risk_score', sa.Integer(), nullable=False),
    sa.Column('rules_triggered', sa.JSON(), nullable=True),
    sa.Column('top_factors', sa.JSON(), nullable=True),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('ruleset_version', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('scoring_config_version', sa.String(length=64), nullable=False),
    sa.Column('external_screening_job', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['rd_case_profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_index(op.f('ix_rd_assessments_input_fingerprint'), 'rd_assessments', ['input_fingerprint'], unique=False)
    op.create_index(op.f('ix_rd_assessments_performed_at'), 'rd_assessments', ['performed_at'], unique=False)
    op.create_index(op.f('ix_rd_assessments_profile_id'), 'rd_assessments', ['profile_id'], unique=False)
    op.create_index(op.f('ix_rd_assessments_risk_level'), 'rd_assessments', ['risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rd_assessments_risk_level'), table_name='rd_assessments')
    op.drop_index(op.f('ix_rd_assessments_profile_id'), table_name='rd_assessments')
    op.drop_index(op.f('ix_rd_assessments_performed_at'), table_name='rd_assessments')
    op.drop_index(op.f('ix_rd_assessments_input_fingerprint'), table_name='rd_assessments')
    op.drop_table('rd_assessments')
    op.drop_index(op.f('ix_rd_case_profiles_version_no'), table_name='rd_case_profiles')
    op.drop_index(op.f('ix_rd_case_profiles_input_fingerprint'), table_name='rd_case_profiles')
    op.drop_index(op.f('ix_rd_case_profiles_case_id'), table_name='rd_case_profiles')
    op.drop_table('rd_case_profiles')
    op.drop_index(op.f('ix_rd_case_items_internal_item_code'), table_name='rd_case_items')
    op.drop_index(op.f('ix_rd_case_items_external_item_id'), table_name='rd_case_items')
    op.drop_index(op.f('ix_rd_case_items_case_id'), table_name='rd_case_items')
    op.drop_table('rd_case_items')
    op.drop_index(op.f('ix_rd_cases_tenant_id'), table_name='rd_cases')
    op.drop_index(op.f('ix_rd_cases_status'), table_name='rd_cases')
    op.drop_index(op.f('ix_rd_cases_external_project_id'), table_name='rd_cases')
    op.drop_table('rd_cases')
    # ### end Alembic commands ###
