"""add use_template_json and end_user_template_json to rd_case_profiles

Revision ID: dc39da4eb83b
Revises: d5d215ae851b
Create Date: 2026-02-10 00:00:00.000000

"""


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc39da4eb83b'
down_revision = 'd5d215ae851b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rd_case_profiles', sa.Column('use_template_json', sa.JSON(), nullable=True))
    op.add_column('rd_case_profiles', sa.Column('end_user_template_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rd_case_profiles', 'end_user_template_json')
    op.drop_column('rd_case_profiles', 'use_template_json')
    # ### end Alembic commands ###
