"""init_platform_schema

Revision ID: 081b20be6eae
Revises: 
Create Date: 2026-02-22 20:54:21.222195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '081b20be6eae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plat_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('module_key', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plat_audit_log_action'), 'plat_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_plat_audit_log_created_at'), 'plat_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_plat_audit_log_module_key'), 'plat_audit_log', ['module_key'], unique=False)
    op.create_index(op.f('ix_plat_audit_log_tenant_id'), 'plat_audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_plat_audit_log_user_id'), 'plat_audit_log', ['user_id'], unique=False)
    op.create_table('plat_llm_usage_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('module_key', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plat_llm_usage_log_created_at'), 'plat_llm_usage_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_plat_llm_usage_log_module_key'), 'plat_llm_usage_log', ['module_key'], unique=False)
    op.create_index(op.f('ix_plat_llm_usage_log_tenant_id'), 'plat_llm_usage_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_plat_llm_usage_log_user_id'), 'plat_llm_usage_log', ['user_id'], unique=False)
    op.create_table('plat_module_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_contracts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('health_check_path', sa.String(length=255), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plat_module_registry_key'), 'plat_module_registry', ['key'], unique=True)
    op.create_table('plat_tenant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plat_tenant_slug'), 'plat_tenant', ['slug'], unique=True)
    op.create_table('plat_company',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('name_aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('is_sanctioned', sa.Boolean(), nullable=False),
    sa.Column('sanction_lists', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_screened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('screening_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_end_user', sa.Boolean(), nullable=False),
    sa.Column('is_consignee', sa.Boolean(), nullable=False),
    sa.Column('end_use_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['plat_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plat_company_name'), 'plat_company', ['name'], unique=False)
    op.create_index(op.f('ix_plat_company_tenant_id'), 'plat_company', ['tenant_id'], unique=False)
    op.create_table('plat_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('auth_provider', sa.String(length=50), nullable=False),
    sa.Column('oauth_sub', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['plat_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plat_user_email'), 'plat_user', ['email'], unique=True)
    op.create_index(op.f('ix_plat_user_oauth_sub'), 'plat_user', ['oauth_sub'], unique=False)
    op.create_index(op.f('ix_plat_user_tenant_id'), 'plat_user', ['tenant_id'], unique=False)
    op.create_table('plat_company_screening_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('screened_by_user_id', sa.UUID(), nullable=True),
    sa.Column('lists_checked', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_is_hit', sa.Boolean(), nullable=False),
    sa.Column('result_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('screened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['plat_company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plat_company_screening_history_company_id'), 'plat_company_screening_history', ['company_id'], unique=False)
    op.create_table('plat_user_module_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('module_key', sa.String(length=100), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_write', sa.Boolean(), nullable=False),
    sa.Column('can_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['plat_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plat_user_module_permission')
    op.drop_index(op.f('ix_plat_company_screening_history_company_id'), table_name='plat_company_screening_history')
    op.drop_table('plat_company_screening_history')
    op.drop_index(op.f('ix_plat_user_tenant_id'), table_name='plat_user')
    op.drop_index(op.f('ix_plat_user_oauth_sub'), table_name='plat_user')
    op.drop_index(op.f('ix_plat_user_email'), table_name='plat_user')
    op.drop_table('plat_user')
    op.drop_index(op.f('ix_plat_company_tenant_id'), table_name='plat_company')
    op.drop_index(op.f('ix_plat_company_name'), table_name='plat_company')
    op.drop_table('plat_company')
    op.drop_index(op.f('ix_plat_tenant_slug'), table_name='plat_tenant')
    op.drop_table('plat_tenant')
    op.drop_index(op.f('ix_plat_module_registry_key'), table_name='plat_module_registry')
    op.drop_table('plat_module_registry')
    op.drop_index(op.f('ix_plat_llm_usage_log_user_id'), table_name='plat_llm_usage_log')
    op.drop_index(op.f('ix_plat_llm_usage_log_tenant_id'), table_name='plat_llm_usage_log')
    op.drop_index(op.f('ix_plat_llm_usage_log_module_key'), table_name='plat_llm_usage_log')
    op.drop_index(op.f('ix_plat_llm_usage_log_created_at'), table_name='plat_llm_usage_log')
    op.drop_table('plat_llm_usage_log')
    op.drop_index(op.f('ix_plat_audit_log_user_id'), table_name='plat_audit_log')
    op.drop_index(op.f('ix_plat_audit_log_tenant_id'), table_name='plat_audit_log')
    op.drop_index(op.f('ix_plat_audit_log_module_key'), table_name='plat_audit_log')
    op.drop_index(op.f('ix_plat_audit_log_created_at'), table_name='plat_audit_log')
    op.drop_index(op.f('ix_plat_audit_log_action'), table_name='plat_audit_log')
    op.drop_table('plat_audit_log')
    # ### end Alembic commands ###
