"""init

Revision ID: 7e4eb9c87ced
Revises: 
Create Date: 2026-01-22 22:18:00.526793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4eb9c87ced'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hs_code', sa.String(length=32), nullable=True),
    sa.Column('eccn', sa.String(length=32), nullable=True),
    sa.Column('ghs_signal_word', sa.String(length=50), nullable=True),
    sa.Column('ghs_pictograms', sa.String(length=255), nullable=True),
    sa.Column('ghs_h_statements', sa.Text(), nullable=True),
    sa.Column('ghs_p_statements', sa.Text(), nullable=True),
    sa.Column('ghs_classes', sa.Text(), nullable=True),
    sa.Column('is_poison', sa.Boolean(), nullable=True),
    sa.Column('is_deleterious', sa.Boolean(), nullable=True),
    sa.Column('is_kashinho', sa.Boolean(), nullable=True),
    sa.Column('is_kashinho_class_I', sa.Boolean(), nullable=True),
    sa.Column('is_kashinho_class_II', sa.Boolean(), nullable=True),
    sa.Column('is_roudou_anzen_eisei', sa.Boolean(), nullable=True),
    sa.Column('is_prtr', sa.Boolean(), nullable=True),
    sa.Column('is_shoubouho', sa.Boolean(), nullable=True),
    sa.Column('is_high_pressure_gas', sa.Boolean(), nullable=True),
    sa.Column('regulation_ai_raw', sa.Text(), nullable=True),
    sa.Column('sds_file_path', sa.String(length=255), nullable=True),
    sa.Column('item_class', sa.String(length=100), nullable=True),
    sa.Column('std_price', sa.Float(), nullable=True),
    sa.Column('bom_json', sa.Text(), nullable=True),
    sa.Column('export_control_status', sa.String(length=50), nullable=False),
    sa.Column('export_control_reason', sa.Text(), nullable=True),
    sa.Column('export_control_checked_at', sa.DateTime(), nullable=True),
    sa.Column('external_eval_status', sa.String(length=50), nullable=True),
    sa.Column('external_eval_reason', sa.Text(), nullable=True),
    sa.Column('external_eval_payload', sa.Text(), nullable=True),
    sa.Column('external_eval_requested_at', sa.DateTime(), nullable=True),
    sa.Column('external_eval_received_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('bom_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('bom_json', sa.Text(), nullable=False),
    sa.Column('total_ratio', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_history_id'), 'bom_history', ['id'], unique=False)
    op.create_index(op.f('ix_bom_history_product_id'), 'bom_history', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bom_history_product_id'), table_name='bom_history')
    op.drop_index(op.f('ix_bom_history_id'), table_name='bom_history')
    op.drop_table('bom_history')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
